#!/bin/bash

rm db.sqlite3
find . -type f -name '000*.py' -exec rm {} +
python3.5 manage.py makemigrations
python3.5 manage.py migrate
python3.5 manage.py loaddata apps/locations/fixtures/state.json
python3.5 manage.py loaddata apps/locations/fixtures/zipcode.json
