# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('state', models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.CASCADE, to='locations.State')),
            ],
            options={
                'db_table': 'zipcode',
                'ordering': ['code'],
            },
        ),
    ]
